coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch:
      default:
        if_no_uploads: success
        if_ci_failed: error
    changes: true
    project:
      default:
        target: auto
        if_no_uploads: error
comment: false