name: Publish release to Java

inputs:
  java-version:
    required: true
  ossr-username:
    required: true
  ossr-token:
    required: true
  signing-key:
    required: true
  signing-password:
    required: true

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      shell: bash
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk list java
        sdk install java ${{ inputs.java-version }} && sdk default java ${{ inputs.java-version }}
        export JAVA_HOME=${SDKMAN_DIR}/candidates/java/current
        echo "JAVA_HOME is set to $JAVA_HOME"

    - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # pin@1.1.0
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}

    - name: Publish Android/Java Packages to Maven
      shell: bash
      run: ./gradlew publish -PisSnapshot=false --stacktrace
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
        MAVEN_USERNAME: ${{ inputs.ossr-username }}
        MAVEN_PASSWORD: ${{ inputs.ossr-token }}
        SIGNING_KEY: ${{ inputs.signing-key}}
        SIGNING_PASSWORD: ${{ inputs.signing-password}}