name: auth0/java-jwt/build-and-test

on:
  pull_request:
  merge_group:
  push:
    branches: ["master", "main", "v1"]

jobs:
  gradle:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

      - name: Test and Assemble and ApiDiff with Gradle
        run: ./gradlew assemble apiDiff check jacocoTestReport --continue --console=plain

      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          flags: unittests
      - uses: actions/upload-artifact@v6
        with:
          name: Reports
          path: lib/build/reports
