name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    name: "validation/gradlew"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # pin@v6.1.1