name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    name: "validation/gradlew"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@0f4528296b4bc09e8ae0fc7be30185a4ab435545 # pin@v6.0.0