name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    name: "validation/gradlew"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # pin@v6.0.1